spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eattofit?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: ENC(y1+j1P+vb0RNE/gzZFvcqg==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
  data:
    redis:
      host: localhost
      port: 6379
      password:
  ai:
    openai:
      api-key: ENC(z2qI+jL6Ws27r00O+vkSWFRGmz84Wckkc+OePq1eVM/nLcdTj9WclhbaMbKy3wU2y9FtGRwdrGttK0DfNSS2N6ejQRcBZbTZRBoWg3jmPHOdyihXDKlO1/+oMW7BzgJS1dpWV1BBFhcNPkSUs2eYfvz1sGzltgapZrI4nBraFec4aH8csX7Eoc95JM18ZCCDYDeatYDUTayPN/3Ed5rwXpan0tTjZfUFjn+3VQ8NML8=)
oauth:
  properties:
    kakao:
      client-id: ENC(QahdImLySFINbtK52eMYXQv9Dm9SrYkOjJaU4BFHjS7vTYWSwP4VE2JSE+Wo/dnf)
      redirect-uri: http://localhost:8080/oauth/kakao
      token-uri: https://kauth.kakao.com/oauth/token?
      user-info-uri: https://kapi.kakao.com/v2/user/me
      user-info-key-word-request:
        email-key-word: kakao_account.email
        name-key-word: kakao_account.profile.nickname
    google:
      client-id: ENC(18xsgD2hCLmKCfqC7JM3CleSIDlAD32uzumpZgUnCg83IO04s2Oynp7Icvyvd09N2IpnMNrbvptsnK5igtWFfu44EaJdcys+NrEzgVAkwwYRUbWdXV28Sw==)
      client-secret: ENC(GQx+sOKJVoGRXl+Eqx0uNSsJMe3rcTQAUbUB8o6zg846KeDf7qrwJZhWZzXj349E)
      redirect-uri: http://localhost:8080/oauth/google
      token-uri: https://oauth2.googleapis.com/token?
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      user-info-key-word-request:
        email-key-word: email
        name-key-word: name
doinglab:
  api-endpoint: ENC(O3b6cfwWip3e8/3McJdSZXt6eHOHbb8m/M1n9ADEqdNBt0wjgoKQCre1Aa8nhery)
  authorization: ENC(9H9Zabe/nbX4OPaE/RBtfvn/g1BMEXBWOZLAuOmpk5vO9sc8nfrdpZOZxzwLyjOGqMEpwJ9ZynEvyxMzAMk2yPXFg5aD7y/5)
  api-version: v2
  app-device-id: ENC(Rh/uuQPYZfYTTFpf0jZ/xrnAM7G+LLZ0OVZDdaOyaow=)
  app-device: android
  app-package: devholic.eattofit
  app-token: ENC(Mboc1qaTFxxkYFOM7/3mUbSxeAb0ooACum+xW2vUhJsNG+D4sEJo01iYEvRQ/TyF)
  company-token: ENC(YN/MbV1yDoc2VarYBomQCsWDzTLpIS/n4DGl8RwotGN6gZMJNA20CkFnXSnJZjvM)
  app-version: 1.0.0
  user-agent: UserAgent
