CREATE TABLE exercise_profile(
    id BIGINT NOT NULL AUTO_INCREMENT,
    experience ENUM('INITIAL', 'UNDER_THREE_MONTH', 'UNDER_SIX_MONTH', 'UNDER_ONE_YEAR', 'OVER_ONE_YEAR') NOT NULL,
    frequency ENUM('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', 'SIX', 'EVERYDAY') NOT NULL,
    goal ENUM('INCREASE_MUSCLE', 'MAINTAIN', 'DIET') NOT NULL,
    level ENUM('NOT_EXPERIENCED', 'NEWBIE', 'INTERMEDIATE', 'EXPERT') NOT NULL,
    member_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);
