name: F-Lab SonarCloud Code Analyze

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  CACHED_DEPENDENCIES_PATHS: '**/node_modules'

jobs:
  CodeAnalyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set SonarCloud Project Key
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
          ORG_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
          SONAR_PROJECT_KEY="${ORG_NAME}_${REPO_NAME}"
          echo "SONAR_PROJECT_KEY=$SONAR_PROJECT_KEY" >> $GITHUB_ENV 

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Create and inject jasypt secret into application-secret.properties
        run: |
          touch ./src/main/resources/application-secret.properties
          echo "${{ secrets.ENCRYPT_KEY }}" > ./src/main/resources/application-secret.properties
          cat ./src/main/resources/application-secret.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build the project
        run: ./gradlew build

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        id: analyze-sonarcloud
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_BOT }}
          SONAR_TOKEN: ${{ secrets.SECRET_SONARQUBE }}
        with:
          args: |
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=f-lab-edu-1
            -Dsonar.java.binaries=build/classes
